In [23]:
from utils.dataloader import DataLoader, train_dataset, test_dataset
batch_size = 34
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=True, drop_last=False)

len(test_loader.dataset)
test_loader.dataset.y

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], shape=(10000, 10))

In [5]:
from utils import candle

candle.is_grad_enabled()

with candle.no_grad():
    print(candle.is_grad_enabled())

False


In [1]:
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])
f = np.array([[7, 8], [9, 10]])

b.T @ f

array([[43, 48],
       [59, 66],
       [75, 84]])

In [12]:
True and True

True

In [ ]:
if not False:
    print("False")

False


In [3]:
(f.T @ b).T

array([[43, 48],
       [59, 66],
       [75, 84]])

In [6]:
dict_ = {"side": "test"}

try:
    start_index = dict_["start_index"]
    end_index = dict_["end_index"]
    matrix_side = dict_["matrix"]
except:
    start_index = None
    end_index = None
    matrix_side = None

side = dict_["side"]

if "matrix" in dict_:
    print("test1")

if 2 != None:
    print("test2")

test2


In [ ]:
import numpy as np

# Create two 3D matrices (tensors)
# For valid matrix multiplication with shape (a, b, c) @ (a, c, d) -> (a, b, d)
A = np.random.randint(0, 10, (2, 3, 4))
B = np.random.randint(0, 10, (2, 4, 5))

# Multiply each (i)th 3x4 with (i)th 4x5 -> each result (i) is 3x5. All dims used.
C = np.empty((2, 3, 5), dtype=int)
for i in range(A.shape[0]):
    C[i] = A[i] @ B[i]

print("A.shape:", A.shape)
print("B.shape:", B.shape)
print("C.shape:", C.shape)
print(C)


[[[1 1 3 1]
  [4 8 3 3]
  [9 2 9 7]]

 [[8 1 3 2]
  [4 9 0 4]
  [5 0 7 5]]]
A.shape: (2, 3, 4)
B.shape: (2, 4, 5)
C.shape: (2, 3, 5)
[[[ 40  18  26  16  42]
  [120  62  99  55 107]
  [160  82  89  96 196]]

 [[ 43  19  93  55  87]
  [ 20  33  62  33  63]
  [ 46  30 104  86  87]]]
